import type { Metadata } from "next";
import "./globals.css";
import Footer from "./Components/Footer";
import Header from "./Components/Header";
import { Roboto, Poppins } from "next/font/google";
import { CartProvider } from "./Context/CartContext";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], 
  variable: "--font-roboto",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500",  "600" , "700", "800"], 
  variable: "--font-poppins",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${poppins.variable} font-sans`}>
          
         <Header/>
         <CartProvider>{children}</CartProvider>
         <Footer/>
      </body>
    </html>
  );
}
